
server:
  port: 8081

spring:
  data:
    rest:
      base-path: api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tpg_office_db
    username: tpg_app
    password: tpgapp_pass
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update